### ISSUE TITLE
Swaps are not imported correctly

### ISSUE THREAD

**Issue by Dschaenson** [geldmacher/Cake-to-CoinTracking-Converter#10] opened 2021-11-28 12:01 UTC
Liegt vermutlich daran, dass swaps aktuell als "unknown" Transaktion in die CSV exportiert werden. Folglich kann Converter damit nicht umgehen. 
VG

**Comment by geldmacher** [comment] 2021-11-28 18:02
Due to wrong data in the current Cake export i have disabled the swap conversion until the export is fixed. Please let me now when this is the case.

Currently there are 3 data records for each swap. One is marked as normal "Deposit" (Incoming transaction from swap), the other two are marked "unknown" (Outgoing transaction for swap and fee for swap). This is the main problem atm.

Normally a Cake swap is converted to a CoinTracking trade. The old swap data from Cake still works this way. The new swap will be converted accordingly when the Cake export was corrected.

See: https://github.com/geldmacher/Cake-to-CoinTracking-Converter/releases/tag/v4.3.1

**Comment by fhopeman** [comment] 2021-12-28 10:41
I opened a case on cake defi about the "unknown" issue. I will give a short feedback here if I get an answer.

**Comment by geldmacher** [comment] 2021-12-28 18:51
I tried to anticipate the correct operation for the two unknown operations and i think it is doable. Please check this release and give me some feedback: https://github.com/geldmacher/Cake-to-CoinTracking-Converter/releases/tag/v4.5.0

**Comment by fhopeman** [comment] 2021-12-31 08:10
Thank you very much :) I tested it right now and it works fine as far as I see. I also got answer to my ticket on cake defi. They will investigate the "unknown" issue with the development team.

Best regards
Fabian

**Comment by fhopeman** [comment] 2021-12-31 08:29
I identified a problem.. but maybe it's layer 8?! I have many warnings like this:

"There is no suitable purchase to this fee (all purchasing pools consumed). Assuming purchase on the same day for 0 EUR."

In my transaction overview I have all the deposits listed like this:

"Deposit | 0.00472826 | BTC |   |   |   |   | Cake | Deposit | Deposit"

But the connection between them doesn't seem to be recognized.

**Comment by geldmacher** [comment] 2022-01-02 07:41
What ist layer 8? ...

**Comment by fhopeman** [comment] 2022-01-02 19:02
That I made a mistake while importing the csv file or missed something else. You can say layer 8 when the problem is in front of the display and not a problem with the tool/system. It's inspired from the ISO/OSI model..

**Comment by geldmacher** [comment] 2022-01-05 11:26
Hmm, i don't have this problem. Strange ... Are you sure, that this error is related to the data from cake? And did you include all coins and assets from cake with no time limitation in your cake export?

**Comment by fhopeman** [comment] 2022-01-06 18:18
I tried it again with only two entries in my csv. I used your tool to generate the entries.

**That's my cointracking overview:**
```
Typ,"Kauf","Cur.","Verkauf","Cur.","Gebühr","Cur.","Börse","Gruppe","Kommentar","Datum"
Einzahlung,"0.00472826","BTC","","","","","Cake","Deposit","Deposit","19.12.2021 15:54:51"
Trade,"30.11744077","DFI","0.00236055","BTC","","","Cake","Swap","Swap trade (DeFiChain DEX)","19.12.2021 16:17:04"
```
I deposit 0.00472826 BTC and buying 30.11744077 DFI with 0.00236055 BTC.

**Thats the result of my tax report:**
```
- | - | - | - | - | 19.12.2021 23:59:59 
Swap von | 0.00236055 | BTC | 30.11744077 | DFI | 19.12.2021 23:59:59
```

- The first entry is only filled with the timestamp. Description says: No pool info
- The second one shows the error: Es liegt kein passender Kauf zu diesem Swap Trade vor (alle Kaufpools erschöpft). Nehme Kauf am gleichen Tag für 0 EUR an.

Maybe you have an idea to fix that. I would be very happy.

**Comment by geldmacher** [comment] 2022-01-07 08:00
I'm not sure if i'm yet getting the whole problem and procedure to reproduce it ( :D ), but it sounds like your are using only a part of the data from Cake. Is this true? If yes, this could be a problem because than there might be some funds missing which CoinTracking needs to calculate the tax report.

Have you tried to delete all imported Cake data from CoinTracking and re-import all of it afterwards?

**Comment by fhopeman** [comment] 2022-01-07 08:25
Yes, I have deleted all data from CoinTracking and re-imported all of them.

I have uploaded my fill cake export here:
https://github.com/fhopeman/tmp/blob/main/2022-01-07_09-18-53_Cake.csv

I generated the cointracking file with the following command:
```
./node_modules/.bin/cake2ct --version
4.6.0

./node_modules/.bin/cake2ct --cake-csv ~/Downloads/2022-01-06_18-36-37_Cake.csv --ct-csv ct.csv --language "DE"
Progress [████████████████████████████████████████] 100% | ETA: 0s | 384/384

Done! Wrote Cake data to CoinTracking file.
```
The result after importing is 42 errors where no buy can be found for the sell.

Maybe you can reproduce it with that if you have time.

**Comment by geldmacher** [comment] 2022-01-07 08:38
This will help for sure, thanks!
I downloaded the data, feel free to delete it. =)

**Comment by fhopeman** [comment] 2022-01-09 15:06
I played a little bit with different imports and I think I found the problem. I just imported the csv generated with your tool. But I assume that I need some further transactions from EUR -> BTC, because otherwise the deposits are not used in the tax report. I will try that with the whole csv later on.. but that should be the solution for me. Thank you a lot for maintaining the tool.

**Comment by geldmacher** [comment] 2022-01-10 08:20
This could be the case. The sole Cake data is not enough in most cases. I will close this issue for now. Feel free to reopen it if your problem persists.

**Closed by geldmacher** 2022-01-10 08:20 UTC
